# -*- coding: utf-8 -*-
"""Aula 1 - Imersão dados com python Alura - Agosto 2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHQN2dpv-wZhzi-1lQqDKxtg1vOuUrxa
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

df.head(10)

df.info()

df.describe()

df.shape

linhas, colunas = df.shape[0], df.shape[1]
print("linhas:",linhas,"colunas:",colunas)

df.columns



df.rename(columns={
    'work_year': 'ano',
    'experience_level': 'senioridade',
    'employment_type': 'contrato',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': 'usd',
    'employee_residence': 'residencia',
    'remote_ratio': 'remoto',
    'company_location': 'empresa',
    'company_size': 'tamanho_empresa'
}, inplace=True)

df.head()

df['senioridade'].value_counts()

df['contrato'].value_counts()

df['remoto'].value_counts()

df['tamanho_empresa'].value_counts()

senioridade = {'SE':'Senior', 'MI':'Pleno', 'EN':'Junior', 'EX': 'Executivo'}
df['senioridade'] = df['senioridade'].replace(senioridade)
df['senioridade'].value_counts()

contrato = {'FT': 'Integral', 'PT': 'Parcial', 'CT': 'Contrato', 'FL': 'Freelance'}
df['contrato'] = df['contrato'].replace(contrato)
df['contrato'].value_counts()

tamanho_empresa = {'L': 'Grande', 'S': 'Pequena', 'M':'Média'}
df['tamanho_empresa'] = df['tamanho_empresa'].replace(tamanho_empresa)
df['tamanho_empresa'].value_counts()

mapa_trabalho = {0: 'Presencial', 100: 'Remoto', 50: 'hibrido'}
df['remoto'] = df['remoto'].replace(mapa_trabalho)
df['remoto'].value_counts()

df.head()

df.describe(include='object')